<a href="https://colab.research.google.com/github/niki2805/Machine-learning/blob/main/KNN_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
dataset = [[2.7810836,2.550537003,0],
	[1.465489372,2.362125076,0],
	[3.396561688,4.400293529,0],
	[1.38807019,1.850220317,0],
	[3.06407232,3.005305973,0],
	[7.627531214,2.759262235,1],
	[5.332441248,2.088626775,1],
	[6.922596716,1.77106367,1],
	[8.675418651,-0.242068655,1],
	[7.673756466,3.508563011,1]]

In [ ]:
dataset

[[2.7810836, 2.550537003, 0],
 [1.465489372, 2.362125076, 0],
 [3.396561688, 4.400293529, 0],
 [1.38807019, 1.850220317, 0],
 [3.06407232, 3.005305973, 0],
 [7.627531214, 2.759262235, 1],
 [5.332441248, 2.088626775, 1],
 [6.922596716, 1.77106367, 1],
 [8.675418651, -0.242068655, 1],
 [7.673756466, 3.508563011, 1]]

In [ ]:
import numpy as np
import pandas as pd
df = pd.DataFrame(dataset, columns=["x1", "x2", "label"])

In [ ]:
def euc_distance(x,x1):
  return np.sqrt(np.sum((x-x1)**2))

In [ ]:
data = df.values

In [ ]:
x_train = data[:,:-1]
y_train = data[:,-1]

In [ ]:
k=3

In [ ]:
def predictions(x_test):
  y_pred=[]
  for x in x_test:
    distances = [euc_distance(x,t) for t in x_train]
    k_idx = np.argsort(distances)[:k]
    k_nn_labels = [ y_train[i] for i in k_idx]
    most_common = Counter(k_nn_labels).most_common(1)
    y_pred.append(most_common[0][0])

  return y_pred

In [ ]:
x_train[-1]

array([7.67375647, 3.50856301])

In [ ]:
print(predictions(x_train[4:6]))

[np.float64(0.0), np.float64(1.0)]


In [ ]:
y_train[4:6]

array([0., 1.])

In [ ]:
from matplotlib.colors import ListedColormap
from sklearn import datasets
from sklearn.model_selection import train_test_split

cmap = ListedColormap(["#FF0000", "#00FF00", "#0000FF"])


iris = datasets.load_iris()
X, y = iris.data, iris.target

X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=1234
    )

In [ ]:
X_train.shape

(120, 4)

In [ ]:
X_sample = X_train[:10]
y_sample = y_train[:10]

X_test_sample = X_test[:5]
y_test_sample = y_test[:5]

In [ ]:
X_sample

array([[5.1, 2.5, 3. , 1.1],
       [6.2, 2.8, 4.8, 1.8],
       [5. , 3.5, 1.3, 0.3],
       [6.3, 2.8, 5.1, 1.5],
       [6.7, 3. , 5. , 1.7],
       [4.8, 3.4, 1.9, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [5.4, 3.4, 1.7, 0.2],
       [4.6, 3.6, 1. , 0.2],
       [5. , 2.3, 3.3, 1. ]])

In [ ]:
import numpy as np
from collections import Counter

class KNN:
  def __init__(self,k=3):
    self.k=k

  def fit(self,X,y):
    self.X_train= X
    self.y_train = y


  def predict(self,X_test):
    y_pred = [self.get_predictions(x) for x in X_test]
    return np.array(y_pred)

  def get_predictions(self,x):
    distances = [self.get_distance(x,x_train) for x_train in self.X_train]
    k_idx = np.argsort(distances)[:self.k]
    k_nn_labels = [ self.y_train[i] for i in k_idx]
    most_common = Counter(k_nn_labels).most_common(1)

    return most_common[0][0]



  def get_distance(self,x,x_train):
    return np.sqrt(np.sum((x-x_train)**2))


In [ ]:
k=5
clf = KNN(k=k)
clf.fit(X_train,y_train)
predictions = clf.predict(X_test)

In [ ]:
def get_accuracy(y_test,y_pred):
  return np.sum(y_test==y_pred)/len(y_test)

In [ ]:
print(get_accuracy(y_test,predictions))

0.9666666666666667
